server:
  port: 8081

spring:
  application:
    name: supplyfellowchatService
  ai:
    openai:
      api-key:
      engine-name: gpt-4-turbo-preview

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
